# minimal settings
title: "Geyao Gu"
description: "Theoretical chemist, data scientist, stochastic processes"
url: "https://gugeyao.github.io"
baseurl: ""

remote_theme: daattali/beautiful-jekyll

author:"Geyao Gu"

navbar-links:
  Home: ""
  CV: "cv"
  Research: "research"

social-network-links:
  email: "your_email@example.com"
  github: "gugeyao"
  google-scholar: "https://scholar.google.com/citations?user=RRPnkecAAAAJ&hl=en"
markdown: kramdown
highlighter: rouge
