# minimal settings
title: "Geyao Gu"
description: "Theoretical chemist, data scientist, stochastic processes"
url: "https://gugeyao.github.io"
baseurl: ""

remote_theme: daattali/beautiful-jekyll

author:
  name: "Geyao Gu"
  email: "gugeyao24@gmail.com"
  github_username: "gugeyao"

navbar:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# ================================
# Build settings
# ================================

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

